language: node_js
node_js:
  - "stable"

sudo: false

cache:
  directories:
    - node_modules
    - jspm_packages

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi

install:
  - npm install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run ci
